/*
 * Authentication
 *
 * Personio Authentication API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthPostRequest {
    /// API Client id
    #[serde(rename = "client_id")]
    pub client_id: String,
    /// API Client secret
    #[serde(rename = "client_secret")]
    pub client_secret: String,
}

impl AuthPostRequest {
    pub fn new(client_id: String, client_secret: String) -> AuthPostRequest {
        AuthPostRequest {
            client_id,
            client_secret,
        }
    }
}

