/*
 * Authentication
 *
 * Personio Authentication API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationTokenResponseAllOfData {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "expires_in", skip_serializing_if = "Option::is_none")]
    pub expires_in: Option<f64>,
    #[serde(rename = "scope", skip_serializing_if = "Option::is_none")]
    pub scope: Option<String>,
}

impl AuthenticationTokenResponseAllOfData {
    pub fn new(token: String) -> AuthenticationTokenResponseAllOfData {
        AuthenticationTokenResponseAllOfData {
            token,
            expires_in: None,
            scope: None,
        }
    }
}

