/*
 * Authentication
 *
 * Personio Authentication API
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationTokenResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "data")]
    pub data: Box<models::AuthenticationTokenResponseAllOfData>,
}

impl AuthenticationTokenResponse {
    pub fn new(success: bool, data: models::AuthenticationTokenResponseAllOfData) -> AuthenticationTokenResponse {
        AuthenticationTokenResponse {
            success,
            data: Box::new(data),
        }
    }
}

