#!/usr/bin/env bash
PERSONIO_AUTH_API=https://raw.githubusercontent.com/personio/api-docs/refs/heads/master/personio-auth-api.yaml
PERSONIO_AUTH_API_PACKAGE=personio-auth

PERSONIO_PERSONNEL_API=https://raw.githubusercontent.com/personio/api-docs/refs/heads/master/personio-personnel-data-api-oa3.yaml
PERSONIO_PERSONNEL_API_PACKAGE=personio-personnel

# Generate rust code for the Auth-API
docker run -u $(id -u):$(id -g) --rm \
    -v $PWD:/local openapitools/openapi-generator-cli generate \
    -i $PERSONIO_AUTH_API \
    -g rust \
    --additional-properties=packageName=$PERSONIO_AUTH_API_PACKAGE \
    -o /local/$PERSONIO_AUTH_API_PACKAGE

# Generate rust code for the Personnel-API
docker run -u $(id -u):$(id -g) --rm \
    -v $PWD:/local openapitools/openapi-generator-cli generate \
    -i $PERSONIO_PERSONNEL_API \
    -g rust \
    -o /local/$PERSONIO_PERSONNEL_API_PACKAGE \
    --additional-properties=packageName=$PERSONIO_PERSONNEL_API_PACKAGE \
    --template-dir /local/templates


