/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyAbsencePeriodsPost201Response {
    #[serde(rename = "data", skip_serializing_if = "Option::is_none")]
    pub data: Option<Box<models::HourlyAbsencePeriodResponse>>,
}

impl CompanyAbsencePeriodsPost201Response {
    pub fn new() -> CompanyAbsencePeriodsPost201Response {
        CompanyAbsencePeriodsPost201Response {
            data: None,
        }
    }
}

