/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyAttendancesProjectsPost400Response {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<Box<models::CompanyAttendancesProjectsPost400ResponseError>>,
}

impl CompanyAttendancesProjectsPost400Response {
    pub fn new() -> CompanyAttendancesProjectsPost400Response {
        CompanyAttendancesProjectsPost400Response {
            success: None,
            error: None,
        }
    }
}

