/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbsenceOverviewAttribute {
    #[serde(rename = "attribute_id", skip_serializing_if = "Option::is_none")]
    pub attribute_id: Option<String>,
    #[serde(rename = "data_type", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<DataType>,
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "duration_days", skip_serializing_if = "Option::is_none")]
    pub duration_days: Option<String>,
    #[serde(rename = "duration_hours", skip_serializing_if = "Option::is_none")]
    pub duration_hours: Option<String>,
    #[serde(rename = "employee_id", skip_serializing_if = "Option::is_none")]
    pub employee_id: Option<i32>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl AbsenceOverviewAttribute {
    pub fn new() -> AbsenceOverviewAttribute {
        AbsenceOverviewAttribute {
            attribute_id: None,
            data_type: None,
            start_date: None,
            end_date: None,
            duration_days: None,
            duration_hours: None,
            employee_id: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "ABSENCE_OVERVIEW")]
    AbsenceOverview,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::AbsenceOverview
    }
}

