/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbsencePeriodBreakdown {
    #[serde(rename = "date")]
    pub date: String,
    /// Number representing the value of duration in minutes.
    #[serde(rename = "effective_duration")]
    pub effective_duration: i32,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl AbsencePeriodBreakdown {
    pub fn new(date: String, effective_duration: i32) -> AbsencePeriodBreakdown {
        AbsencePeriodBreakdown {
            date,
            effective_duration,
            additional_properties: std::collections::HashMap::new(),
        }
    }
}

