/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AbsencePeriodAttribute {
    #[serde(rename = "attribute_id", skip_serializing_if = "Option::is_none")]
    pub attribute_id: Option<String>,
    #[serde(rename = "data_type", skip_serializing_if = "Option::is_none")]
    pub data_type: Option<DataType>,
    #[serde(rename = "start_date", skip_serializing_if = "Option::is_none")]
    pub start_date: Option<String>,
    #[serde(rename = "end_date", skip_serializing_if = "Option::is_none")]
    pub end_date: Option<String>,
    #[serde(rename = "half_day_at_start", skip_serializing_if = "Option::is_none")]
    pub half_day_at_start: Option<bool>,
    #[serde(rename = "half_day_at_end", skip_serializing_if = "Option::is_none")]
    pub half_day_at_end: Option<bool>,
    #[serde(rename = "employee_id", skip_serializing_if = "Option::is_none")]
    pub employee_id: Option<i32>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl AbsencePeriodAttribute {
    pub fn new() -> AbsencePeriodAttribute {
        AbsencePeriodAttribute {
            attribute_id: None,
            data_type: None,
            start_date: None,
            end_date: None,
            half_day_at_start: None,
            half_day_at_end: None,
            employee_id: None,
            additional_properties: std::collections::HashMap::new(),
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DataType {
    #[serde(rename = "ABSENCE_PERIOD")]
    AbsencePeriod,
}

impl Default for DataType {
    fn default() -> DataType {
        Self::AbsencePeriod
    }
}

