/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendanceCreateRequest {
    #[serde(rename = "attendances", skip_serializing_if = "Option::is_none")]
    pub attendances: Option<Vec<models::AttendanceCreateRequestAttendancesInner>>,
    /// Optional, default value is true. If set to false, the approval status of the attendance period will be \"pending\" if an approval rule is set for the attendances type. The respective approval flow will be triggered.
    #[serde(rename = "skip_approval", skip_serializing_if = "Option::is_none")]
    pub skip_approval: Option<bool>,
}

impl AttendanceCreateRequest {
    pub fn new() -> AttendanceCreateRequest {
        AttendanceCreateRequest {
            attendances: None,
            skip_approval: None,
        }
    }
}

