/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AttendanceCreateUpdate400ErrorResponseErrorDetailedMessageInner {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "error_msg", skip_serializing_if = "Option::is_none")]
    pub error_msg: Option<String>,
    #[serde(rename = "id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub id: Option<Option<i32>>,
    #[serde(rename = "employee", skip_serializing_if = "Option::is_none")]
    pub employee: Option<i32>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "start_time", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,
    #[serde(rename = "end_time", skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
    #[serde(rename = "break", skip_serializing_if = "Option::is_none")]
    pub r#break: Option<i32>,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,
    #[serde(rename = "project_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<Option<i32>>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl AttendanceCreateUpdate400ErrorResponseErrorDetailedMessageInner {
    pub fn new() -> AttendanceCreateUpdate400ErrorResponseErrorDetailedMessageInner {
        AttendanceCreateUpdate400ErrorResponseErrorDetailedMessageInner {
            success: None,
            error_msg: None,
            id: None,
            employee: None,
            date: None,
            start_time: None,
            end_time: None,
            r#break: None,
            comment: None,
            project_id: None,
        }
    }
}

