/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentUploadFailedWithUnsupportedFileTypeResponseAllOfErrorErrorData {
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Vec<String>>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl DocumentUploadFailedWithUnsupportedFileTypeResponseAllOfErrorErrorData {
    pub fn new() -> DocumentUploadFailedWithUnsupportedFileTypeResponseAllOfErrorErrorData {
        DocumentUploadFailedWithUnsupportedFileTypeResponseAllOfErrorErrorData {
            file: None,
        }
    }
}

