/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HourlyAbsencePeriodsResponseAllOfData {
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<serde_json::Value>,
    #[serde(rename = "attributes")]
    pub attributes: Box<models::HourlyAbsence>,
}

impl HourlyAbsencePeriodsResponseAllOfData {
    pub fn new(r#type: Option<serde_json::Value>, attributes: models::HourlyAbsence) -> HourlyAbsencePeriodsResponseAllOfData {
        HourlyAbsencePeriodsResponseAllOfData {
            r#type,
            attributes: Box::new(attributes),
        }
    }
}

