/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HourlyAbsencePeriodResponse {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "data")]
    pub data: Box<models::HourlyAbsencePeriodsResponseAllOfData>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl HourlyAbsencePeriodResponse {
    pub fn new(success: bool, data: models::HourlyAbsencePeriodsResponseAllOfData) -> HourlyAbsencePeriodResponse {
        HourlyAbsencePeriodResponse {
            success,
            data: Box::new(data),
        }
    }
}

