/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceTarget {
    #[serde(rename = "performance_target_id", skip_serializing_if = "Option::is_none")]
    pub performance_target_id: Option<String>,
    #[serde(rename = "performance_target_value", skip_serializing_if = "Option::is_none")]
    pub performance_target_value: Option<String>,
}

impl PerformanceTarget {
    pub fn new() -> PerformanceTarget {
        PerformanceTarget {
            performance_target_id: None,
            performance_target_value: None,
        }
    }
}

