/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceTargetKpi {
    #[serde(rename = "performance_target_id", skip_serializing_if = "Option::is_none")]
    pub performance_target_id: Option<String>,
    #[serde(rename = "performance_kpis", skip_serializing_if = "Option::is_none")]
    pub performance_kpis: Option<Vec<models::PerformanceKpi>>,
}

impl PerformanceTargetKpi {
    pub fn new() -> PerformanceTargetKpi {
        PerformanceTargetKpi {
            performance_target_id: None,
            performance_kpis: None,
        }
    }
}

