/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PerformanceKpi {
    #[serde(rename = "performance_kpi_id", skip_serializing_if = "Option::is_none")]
    pub performance_kpi_id: Option<String>,
    #[serde(rename = "performance_kpi_value", skip_serializing_if = "Option::is_none")]
    pub performance_kpi_value: Option<String>,
}

impl PerformanceKpi {
    pub fn new() -> PerformanceKpi {
        PerformanceKpi {
            performance_kpi_id: None,
            performance_kpi_value: None,
        }
    }
}

