/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicReportAttributesFiltersInner {
    #[serde(rename = "column", skip_serializing_if = "Option::is_none")]
    pub column: Option<String>,
    #[serde(rename = "comparison", skip_serializing_if = "Option::is_none")]
    pub comparison: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl PublicReportAttributesFiltersInner {
    pub fn new() -> PublicReportAttributesFiltersInner {
        PublicReportAttributesFiltersInner {
            column: None,
            comparison: None,
            value: None,
        }
    }
}

