/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicReportItemsAttributesItemsInner {
    #[serde(rename = "employee_id", skip_serializing_if = "Option::is_none")]
    pub employee_id: Option<i32>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<models::PublicReportItemsAttributesItemsInnerAttributesInner>>,
}

impl PublicReportItemsAttributesItemsInner {
    pub fn new() -> PublicReportItemsAttributesItemsInner {
        PublicReportItemsAttributesItemsInner {
            employee_id: None,
            attributes: None,
        }
    }
}

