/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeOffTypeResource {
    /// Time-off type resource name
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<Type>,
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Box<models::TimeOffTypeResourceAttributes>>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl TimeOffTypeResource {
    pub fn new() -> TimeOffTypeResource {
        TimeOffTypeResource {
            r#type: None,
            attributes: None,
        }
    }
}
/// Time-off type resource name
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "TimeOffType")]
    TimeOffType,
}

impl Default for Type {
    fn default() -> Type {
        Self::TimeOffType
    }
}

