/*
 * Personnel Data
 *
 * API for reading and writing personnel data including data about attendances, absences, documents, etc
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkScheduleValueAttributes {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<f64>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<serde_json::Value>>,
    #[serde(rename = "monday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monday: Option<Option<serde_json::Value>>,
    #[serde(rename = "tuesday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tuesday: Option<Option<serde_json::Value>>,
    #[serde(rename = "wednesday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub wednesday: Option<Option<serde_json::Value>>,
    #[serde(rename = "thursday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub thursday: Option<Option<serde_json::Value>>,
    #[serde(rename = "friday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub friday: Option<Option<serde_json::Value>>,
    #[serde(rename = "saturday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub saturday: Option<Option<serde_json::Value>>,
    #[serde(rename = "sunday", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sunday: Option<Option<serde_json::Value>>,
    #[serde(flatten)]
    pub additional_properties: std::collections::HashMap<String, serde_json::Value>,
}

impl WorkScheduleValueAttributes {
    pub fn new() -> WorkScheduleValueAttributes {
        WorkScheduleValueAttributes {
            id: None,
            name: None,
            monday: None,
            tuesday: None,
            wednesday: None,
            thursday: None,
            friday: None,
            saturday: None,
            sunday: None,
            additional_properties: std::collections::HashMap::new(),
        }
    }
}

